source 'https://read_ios_token_2:ZJ8CH9npP4Ar4ZD2bxzS@gitlab.postindustria.com/ar-ring/jewelry-ar-sdk-ios-cocoapods-podspecs.git'
source 'https://cdn.cocoapods.org/'

use_frameworks!

platform :ios, '14.0'

use_frameworks!

target 'JewelryAR_Example' do
  pod 'JewelryAR-SwiftUI'
end
